version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.41
    - 15.0.0
  - dependency-name: "@sasjs/core"
    versions:
    - 2.12.3
    - 2.13.0
    - 2.13.2
    - 2.17.3
    - 2.18.0
    - 2.8.0
    - 2.9.4
  - dependency-name: "@sasjs/utils"
    versions:
    - 2.10.1
    - 2.10.2
    - 2.3.0
    - 2.4.0
    - 2.5.1
    - 2.6.1
    - 2.6.2
    - 2.7.0
    - 2.8.1
    - 2.9.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.7
    - 16.2.9
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@sasjs/adapter"
    versions:
    - 2.1.0
    - 2.1.1
    - 2.2.10
    - 2.2.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: jsdom
    versions:
    - 16.5.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
    - 4.2.3
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.4.0
  - dependency-name: csv-stringify
    versions:
    - 5.6.2
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: fs-extra
    versions:
    - 9.1.0
