name: 'Assign Reviewer'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uesteibar/reviewer-lottery@v1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          groups:
            - name: devs # name of the group
              reviewers: 1 # how many reviewers do you want to assign?
              usernames: # github usernames of the reviewers
                - krishna-acondy
                - YuryShkoda
                - saadjutt01
                - medjedovicm
