# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run mocked tests on Windows

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check code style
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Install Chocolatey
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Doxygen
        run: choco install doxygen.install

      - name: Link
        run: npm link

      - name: npm prefix for user
        run: echo prefix=C:\npm\prefix >> ~\.npmrc

      - name: Run mocked tests
        run: npm run test:mocked
        env:
          CI: true
          CLIENT: ${{secrets.CLIENT}}
          SECRET: ${{secrets.SECRET}}
          SAS_USERNAME: ${{secrets.SAS_USERNAME}}
          SAS_PASSWORD: ${{secrets.SAS_PASSWORD}}
          VIYA_SERVER_URL: ${{secrets.VIYA_SERVER_URL}}
          SAS9_SERVER_URL: ${{secrets.SAS9_SERVER_URL}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}
